### ISSUE TITLE
Potential bug in preprocess_augmentations.py

### ISSUE THREAD

**Issue by john-lennon-chan** [ClinicalDataScience/datacentric-challenge#4]
Dear Organizer,

I am facing errors in running the following code in preprocess_augmentations.py. 

```
for j, i in tqdm(enumerate(valid_files), desc=f"Resuming preprocessing. Validate {len(valid_files)} files"):
            test_file = os.path.join(self.destination, f"{i}_{self.samples_per_file - 1:03d}.npz")
            # Load and process data
            data = np.load(test_file)
            try:
                image = torch.from_numpy(data["input"])
                label = torch.from_numpy(data["label"])
                valid_files.append(test_file)
            except Exception:
                valid_files.pop(j)

        print(f"Found {len(valid_files)} valid files!")
        return valid_files
```

The code appends the test_file back to the list of valid_files, and when we this newly appended elemnt is enumerated, the new test_file formed from this element is an invalid path when self.destination is not an empty string, leading to error. And in addition, even if there is no error, I believe the enumeration might go on forever because there are constantly new elements appending.

And so I would like to ask the organizer for clarifications on how to address this issue. Thank you very much!

Yours sincerely,
Lennon

**Comment by JakobDexl** [comment]
Hi Lennon, 

thanks for the question. The `valid_files.append(test_file)` is a cp error and just needs to be removed. Beside that the code is just for validation the saved files since i had some broken files when using exessive amounts of cpus. You could easily ignore the section. 

Best Jakob

**Comment by john-lennon-chan** [comment]
Dear Jakob,

Thank you very much!

Your sincerely,
Lennon
